/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Mihail Maldzhanski
 */
public class GUIView extends javax.swing.JFrame {

    //Configuration params
    private int countOfElements;
    private int countOfThreads;
    private String outputFile;

    public String getOutputFile() {
        return outputFile;
    }

    //Status
    private boolean isReadyForCalculation;

    public boolean isReadyForCalculation() {
        return isReadyForCalculation;
    }

    public void setIsReadyForCalculation(boolean isReadyForCalculation) {
        this.isReadyForCalculation = isReadyForCalculation;
        btnCalculate.setEnabled(true);
    }

    public int getCountOfElements() {
        return countOfElements;
    }

    private void setCountOfElements(int countOfElements) {
        this.countOfElements = countOfElements;
    }

    public int getCountOfThreads() {
        return countOfThreads;
    }

    private void setCountOfThreads(int countOfThreads) {
        this.countOfThreads = countOfThreads;
    }

    /**
     * Creates new form GUIView
     */
    public GUIView() {
        initComponents();
        setMaxThreads();
        setCountOfElements(1);
        setCountOfThreads(1);
        this.isReadyForCalculation = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalculate = new javax.swing.JButton();
        lblConsole = new javax.swing.JLabel();
        sldThreads = new javax.swing.JSlider();
        sldElements = new javax.swing.JSlider();
        txtFile = new javax.swing.JTextField();
        lblGeneralConfig = new javax.swing.JLabel();
        lblSelectThreads = new javax.swing.JLabel();
        lblSelectElements = new javax.swing.JLabel();
        lblMinElements = new javax.swing.JLabel();
        lblMaxElements = new javax.swing.JLabel();
        lblMinThreads = new javax.swing.JLabel();
        lblMaxThreds = new javax.swing.JLabel();
        txtElements = new javax.swing.JTextField();
        txtThreads = new javax.swing.JTextField();
        lblFile = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multi-Threading Euler Calculator");
        setResizable(false);

        btnCalculate.setText("Calculate Euler");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblConsole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConsole.setText("Output Console");

        sldThreads.setMajorTickSpacing(1);
        sldThreads.setMaximum(8);
        sldThreads.setMinimum(1);
        sldThreads.setMinorTickSpacing(1);
        sldThreads.setToolTipText("");
        sldThreads.setValue(1);
        sldThreads.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldThreadsStateChanged(evt);
            }
        });

        sldElements.setMajorTickSpacing(1000);
        sldElements.setMaximum(50000);
        sldElements.setMinimum(100);
        sldElements.setMinorTickSpacing(1);
        sldElements.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldElementsStateChanged(evt);
            }
        });

        txtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileActionPerformed(evt);
            }
        });

        lblGeneralConfig.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGeneralConfig.setText("General Configuration");

        lblSelectThreads.setText("Select count of Threads");

        lblSelectElements.setText("Select count of Elements");

        lblMinElements.setText("100");

        lblMaxElements.setText("50 000");

        lblMinThreads.setText("1");

        lblMaxThreds.setText("8");

        txtElements.setText("100");
        txtElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtElementsActionPerformed(evt);
            }
        });

        txtThreads.setText("1");
        txtThreads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThreadsActionPerformed(evt);
            }
        });

        lblFile.setText("Select output File Name");

        txtConsole.setColumns(20);
        txtConsole.setRows(5);
        txtConsole.setFocusable(false);
        jScrollPane1.setViewportView(txtConsole);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(txtElements, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMaxElements))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(sldElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(lblMinThreads)
                                                    .addGap(63, 63, 63)
                                                    .addComponent(txtThreads, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblMaxThreds))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sldThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGeneralConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSelectElements)
                                            .addComponent(lblMinElements)
                                            .addComponent(lblSelectThreads)
                                            .addComponent(lblFile))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeneralConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblSelectElements)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinElements)
                            .addComponent(lblMaxElements)
                            .addComponent(txtElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(lblSelectThreads)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinThreads)
                            .addComponent(lblMaxThreds)
                            .addComponent(txtThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(lblFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        this.countOfElements = Integer.parseInt(txtElements.getText());
        this.countOfThreads = Integer.parseInt(txtThreads.getText());
        this.outputFile = txtFile.getText();
        this.isReadyForCalculation = true;
        btnCalculate.setEnabled(false);
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtElementsActionPerformed
        int value = Integer.parseInt(txtElements.getText());
        sldElements.setValue(value);
    }//GEN-LAST:event_txtElementsActionPerformed

    private void txtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileActionPerformed

    private void sldElementsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldElementsStateChanged
        txtElements.setText("" + sldElements.getValue());
    }//GEN-LAST:event_sldElementsStateChanged

    private void sldThreadsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldThreadsStateChanged
        txtThreads.setText("" + sldThreads.getValue());
    }//GEN-LAST:event_sldThreadsStateChanged

    private void txtThreadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThreadsActionPerformed
        int value = Integer.parseInt(txtThreads.getText());
        sldThreads.setValue(value);
    }//GEN-LAST:event_txtThreadsActionPerformed

    private void setMaxThreads() {
        int maxThreads = Runtime.getRuntime().availableProcessors();
        lblMaxThreds.setText("" + maxThreads);
        sldThreads.setMaximum(maxThreads);
    }

    public void setOutputFile(String outputFile) {
        if (!outputFile.equals(this.outputFile)) {
            txtFile.setText(outputFile);
            this.outputFile = outputFile;
        }
    }
    
    public void consoleGUILn(String text){
        String previousText = txtConsole.getText() + "\n";
        txtConsole.setText(previousText + text);
    }

    /**
     * @ Basic start up function
     */
    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsole;
    private javax.swing.JLabel lblFile;
    private javax.swing.JLabel lblGeneralConfig;
    private javax.swing.JLabel lblMaxElements;
    private javax.swing.JLabel lblMaxThreds;
    private javax.swing.JLabel lblMinElements;
    private javax.swing.JLabel lblMinThreads;
    private javax.swing.JLabel lblSelectElements;
    private javax.swing.JLabel lblSelectThreads;
    private javax.swing.JSlider sldElements;
    private javax.swing.JSlider sldThreads;
    private javax.swing.JTextArea txtConsole;
    private javax.swing.JTextField txtElements;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtThreads;
    // End of variables declaration//GEN-END:variables
}
